# Generated by Django 4.0.3 on 2022-04-10 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgentSignUp', '0002_delete_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=80)),
                ('city', models.CharField(max_length=50)),
            ],
        ),
    ]
