# Generated by Django 4.0.3 on 2022-04-10 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgentSignUp', '0004_delete_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('emp_ID', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=40)),
                ('full_name', models.CharField(max_length=80)),
                ('city', models.CharField(max_length=50)),
                ('Mobile', models.CharField(max_length=10)),
                ('isAgent', models.BooleanField()),
            ],
        ),
    ]
