# Generated by Django 4.0.3 on 2022-04-10 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AgentSignUp', '0005_agent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agent',
        ),
    ]
