# Generated by Django 4.0.3 on 2022-04-11 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgentSignUp', '0007_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
