# Generated by Django 4.0.3 on 2022-04-14 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AgentSignUp', '0009_auto_20220413_0206'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agent',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
