pipeline {
    agent none
    stages {
        stage('Build') {
             agent {
                docker {
                    image 'python:3-alpine'
                }
            }
            steps {
                sh 'python -m py_compile StockFlow/manage.py'
                run:
                    command: |
                        python3 -m venv venv
                        . venv/bin/activate
                        pip install -r django-test
            }
        }
        stage('Test') {
            agent {
                docker {
                    image 'qnib/pytest'
                }
            }
            steps {
                sh 'py.test --verbose --junit-xml test-reports/results.xml StockFlow/AgentSignUp/tests/test_AgentSignUp.py'
            }
            post {
                always {
                    junit 'test-reports/results.xml'
                }
            }
        }
    }
}
