pipeline {
    agent none
    stages {
        stage('Build') {
             agent {
                docker {
                    image 'python:3-alpine'
                }
            }
            steps {
                sh 'python -m py_compile StockFlow/manage.py'
            }
        }
        stage('Test') {
            agent {
                docker {
                    image 'django'
                }
            } 
            
            steps {
                always { 
                    cleanWs()
                }
                sh 'python -m compile StockFlow/AgentSignUp/test/test_AgentSignUp.py'
            }
            post {
                always {
                    junit 'test-reports/results.xml'
                }
            }
        }
    }
}
