pipeline {
    agent none
    stages {
        stage('Build') {
             agent {
                docker {
                    image 'python:3-alpine'
                }
            }
            steps {          
                withEnv(["HOME=${env.WORKSPACE}"]){                  
                    sh 'python -m py_compile StockFlow/manage.py'
                }
            }
        }
        stage('Test') {
            agent {
                docker {
                    image 'django'
                    image 'python:3.7'
                }
            } 
            
             steps{
                
                withEnv(["HOME=${env.WORKSPACE}"]){  
                     sh 'pip install -r requirements.txt'
                     dir('StockFlow'){ 
                        sh 'python3 -m coverage run --source="." manage.py test'
                        sh 'python3 -m coverage report'
                        sh 'python3 manage.py check'
                }
                }
             }
        }
    }
}
