# Generated by Django 3.1.3 on 2022-04-12 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_Customer', models.BooleanField(default=False)),
                ('is_Agent', models.BooleanField(default=False)),
                ('is_Admin', models.BooleanField(default=False)),
                ('full_name', models.CharField(max_length=80)),
                ('city', models.CharField(max_length=50)),
                ('Mobile', models.CharField(max_length=10)),
                ('isConfirmedAgent', models.BooleanField(default=False)),
                ('isPortfolio', models.CharField(choices=[('waiting', 'waiting'), ('confirmed', 'confirmed'), ('declined', 'declined'), ('None', 'None')], default='None', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
