# Generated by Django 4.0.3 on 2022-04-14 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_password'),
        ('accounts', '0003_user_is_staff'),
    ]

    operations = [
    ]
